name: Malformed issue template labeler

on:
  issues:
    types: [opened, edited]
    
jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
